/**
 * GURU CHARAN — FRESH PORTFOLIO BACKEND
 *
 * This project is independent of every previous portfolio Apps Script.
 *
 * ONE-TIME SETUP:
 * 1. Paste this file into a blank Apps Script project.
 * 2. Run setupPortfolioSystem().
 * 3. Run installPortfolioAutomation().
 * 4. Deploy as a Web App: Execute as Me; access Anyone.
 * 5. Paste the /exec URL into src/config.ts.
 */

const GC = Object.freeze({
  SITE_NAME: 'Guru Charan — Security Intelligence Universe',
  CONTACT_TO: 'charanmavuduru9273@gmail.com',
  ROOT_FOLDER_NAME: 'Gurucharan Portfolio CMS',
  BLOGS_FOLDER_NAME: 'Blogs',
  MEDIA_FOLDER_NAME: 'Media',
  ARCHIVE_FOLDER_NAME: 'Archive',
  META_FILE: 'portfolio.meta.json',
  CACHE_KEY: 'gc-live-blogs-v5',
  CACHE_SECONDS: 120,
  MAX_BLOGS: 100,
  CONTACT_COOLDOWN_SECONDS: 45,
});

function setupPortfolioSystem() {
  const properties = PropertiesService.getScriptProperties();
  let root;

  const existingRootId = properties.getProperty('GC_ROOT_FOLDER_ID');
  if (existingRootId) {
    try { root = DriveApp.getFolderById(existingRootId); } catch (error) {}
  }

  if (!root) {
    root = DriveApp.createFolder(GC.ROOT_FOLDER_NAME);
    properties.setProperty('GC_ROOT_FOLDER_ID', root.getId());
  }

  const blogs = getOrCreateFolder_(root, GC.BLOGS_FOLDER_NAME);
  const media = getOrCreateFolder_(root, GC.MEDIA_FOLDER_NAME);
  const archive = getOrCreateFolder_(root, GC.ARCHIVE_FOLDER_NAME);

  properties.setProperties({
    GC_BLOGS_FOLDER_ID: blogs.getId(),
    GC_MEDIA_FOLDER_ID: media.getId(),
    GC_ARCHIVE_FOLDER_ID: archive.getId(),
  }, false);

  createCmsReadme_(root);
  createBlogTemplate_(blogs);

  Logger.log('Portfolio CMS ready.');
  Logger.log('Root folder: ' + root.getUrl());
  Logger.log('Blogs folder: ' + blogs.getUrl());

  return {
    ok: true,
    rootFolderId: root.getId(),
    blogsFolderId: blogs.getId(),
    rootUrl: root.getUrl(),
    blogsUrl: blogs.getUrl(),
  };
}

function installPortfolioAutomation() {
  ScriptApp.getProjectTriggers().forEach(function(trigger) {
    if (trigger.getHandlerFunction() === 'syncFutureBlogs') {
      ScriptApp.deleteTrigger(trigger);
    }
  });

  ScriptApp.newTrigger('syncFutureBlogs')
    .timeBased()
    .everyHours(1)
    .create();

  const result = syncFutureBlogs();
  Logger.log('Hourly future-blog automation installed.');
  return { ok: true, initialSync: result };
}

function syncFutureBlogs() {
  const blogsFolder = getBlogsFolder_();
  const folders = blogsFolder.getFolders();
  const results = [];

  while (folders.hasNext()) {
    const folder = folders.next();
    if (folder.getName().indexOf('00_') === 0) continue;

    const doc = findPrimaryDoc_(folder);
    if (!doc) {
      results.push({ folder: folder.getName(), action: 'SKIPPED_NO_DOC' });
      continue;
    }

    const metaFile = findFile_(folder, GC.META_FILE);
    let existing = null;

    if (metaFile) {
      try {
        existing = JSON.parse(metaFile.getBlob().getDataAsString('UTF-8'));
      } catch (error) {}
    }

    if (existing && existing.autoGenerated === false) {
      results.push({ folder: folder.getName(), action: 'PRESERVED_MANUAL' });
      continue;
    }

    const sourceUpdatedAt = existing ? new Date(existing.sourceUpdatedAt || 0).getTime() : 0;
    if (existing && sourceUpdatedAt >= doc.getLastUpdated().getTime()) {
      results.push({ folder: folder.getName(), action: 'CURRENT' });
      continue;
    }

    const metadata = generateMetadata_(folder, doc, existing);
    const json = JSON.stringify(metadata, null, 2);

    if (metaFile) metaFile.setContent(json);
    else folder.createFile(GC.META_FILE, json, MimeType.PLAIN_TEXT);

    results.push({ folder: folder.getName(), action: metaFile ? 'UPDATED' : 'CREATED' });
  }

  CacheService.getScriptCache().remove(GC.CACHE_KEY);
  Logger.log(JSON.stringify(results, null, 2));
  return { ok: true, results: results };
}

function doGet(e) {
  const action = String((e && e.parameter && e.parameter.action) || 'health');

  if (action === 'health') {
    return jsonOrJsonp_({
      ok: true,
      service: GC.SITE_NAME,
      timestamp: new Date().toISOString(),
    }, e);
  }

  if (action === 'blogs') {
    const refresh = String(e.parameter.refresh || '') === '1';
    return jsonOrJsonp_({
      ok: true,
      blogs: getBlogs_(refresh),
    }, e);
  }

  if (action === 'read') {
    return renderArticle_(String(e.parameter.id || ''));
  }

  if (action === 'diagnostics') {
    return jsonOrJsonp_(diagnostics_(), e);
  }

  return jsonOrJsonp_({ ok: false, error: 'Unknown action' }, e);
}

function doPost(e) {
  try {
    const data = e && e.parameter ? e.parameter : {};

    if (String(data.action || '') !== 'contact') {
      return json_({ ok: false, error: 'Unknown action' });
    }

    if (String(data.company_website || '').trim()) {
      return json_({ ok: true });
    }

    const name = clean_(data.name, 100);
    const email = clean_(data.email, 180);
    const subject = clean_(data.subject, 180);
    const message = clean_(data.message, 5000);
    const source = clean_(data.source || 'Portfolio', 180);

    if (!name || !isEmail_(email) || !subject || message.length < 8) {
      return json_({ ok: false, error: 'Please provide valid contact details.' });
    }

    enforceContactCooldown_(email);

    const body = [
      'New portfolio message',
      '',
      'Name: ' + name,
      'Email: ' + email,
      'Subject: ' + subject,
      'Source: ' + source,
      '',
      'Message:',
      message,
      '',
      'Received: ' + new Date().toString(),
    ].join('\n');

    MailApp.sendEmail({
      to: GC.CONTACT_TO,
      subject: '[Portfolio] ' + subject,
      body: body,
      replyTo: email,
      name: GC.SITE_NAME,
    });

    return json_({ ok: true, message: 'Message sent.' });
  } catch (error) {
    return json_({ ok: false, error: error.message });
  }
}

function getBlogs_(refresh) {
  const cache = CacheService.getScriptCache();
  if (!refresh) {
    const cached = cache.get(GC.CACHE_KEY);
    if (cached) return JSON.parse(cached);
  }

  syncFutureBlogs();

  const root = getBlogsFolder_();
  const folders = root.getFolders();
  const blogs = [];

  while (folders.hasNext() && blogs.length < GC.MAX_BLOGS) {
    const folder = folders.next();
    if (folder.getName().indexOf('00_') === 0) continue;

    const doc = findPrimaryDoc_(folder);
    if (!doc) continue;

    const metaFile = findFile_(folder, GC.META_FILE);
    let metadata = {};

    if (metaFile) {
      try { metadata = JSON.parse(metaFile.getBlob().getDataAsString('UTF-8')); }
      catch (error) {}
    }

    const text = DocumentApp.openById(doc.getId()).getBody().getText();
    const wordCount = text.trim() ? text.trim().split(/\s+/).length : 0;

    blogs.push({
      id: doc.getId(),
      slug: metadata.slug || slugify_(metadata.title || doc.getName()),
      title: metadata.title || doc.getName(),
      description: metadata.description || descriptionFromText_(text),
      domain: metadata.domain || inferDomain_(text),
      tags: Array.isArray(metadata.tags) ? metadata.tags : inferTags_(text),
      status: metadata.status || 'Learning note',
      featured: metadata.featured === true,
      updatedAt: doc.getLastUpdated().toISOString(),
      readingTime: Math.max(1, Math.ceil(wordCount / 220)),
      url: ScriptApp.getService().getUrl() + '?action=read&id=' + encodeURIComponent(doc.getId()),
    });
  }

  blogs.sort(function(a, b) {
    if (a.featured !== b.featured) return a.featured ? -1 : 1;
    return new Date(b.updatedAt).getTime() - new Date(a.updatedAt).getTime();
  });

  cache.put(GC.CACHE_KEY, JSON.stringify(blogs), GC.CACHE_SECONDS);
  return blogs;
}

function generateMetadata_(folder, docFile, existing) {
  const text = DocumentApp.openById(docFile.getId()).getBody().getText();
  const lines = text.split('\n').map(function(line) {
    return line.replace(/\s+/g, ' ').trim();
  }).filter(String);

  const explicitTitle = field_(lines, ['Portfolio Title', 'Blog Title']);
  const title = explicitTitle || lines[0] || docFile.getName();

  const explicitDescription = field_(lines, ['Portfolio Description', 'Blog Description']);
  const explicitDomain = field_(lines, ['Portfolio Domain', 'Domain']);
  const explicitTags = field_(lines, ['Portfolio Tags', 'Tags']);
  const explicitStatus = field_(lines, ['Portfolio Status', 'Project Status', 'Status']);
  const explicitFeatured = field_(lines, ['Portfolio Featured', 'Featured']);

  return {
    title: title,
    slug: slugify_(title),
    description: explicitDescription || descriptionFromText_(text),
    domain: explicitDomain || inferDomain_(text + ' ' + folder.getName()),
    tags: explicitTags ? explicitTags.split(/[,;|]/).map(function(tag) { return tag.trim(); }).filter(String) : inferTags_(text),
    status: explicitStatus || inferStatus_(text),
    featured: explicitFeatured ? /^(true|yes|1)$/i.test(explicitFeatured) : Boolean(existing && existing.featured),
    autoGenerated: true,
    sourceDocumentId: docFile.getId(),
    sourceUpdatedAt: docFile.getLastUpdated().toISOString(),
    generatedAt: new Date().toISOString(),
  };
}

function renderArticle_(id) {
  if (!id) return HtmlService.createHtmlOutput('Article ID missing.');

  const file = DriveApp.getFileById(id);
  if (file.getMimeType() !== MimeType.GOOGLE_DOCS) {
    return HtmlService.createHtmlOutput('Unsupported article type.');
  }

  const doc = DocumentApp.openById(id);
  const lines = doc.getBody().getText().split('\n');
  const title = lines.filter(String)[0] || file.getName();
  const content = lines.slice(1).map(function(line) {
    const clean = line.trim();
    if (!clean) return '';
    if (/^#{1,3}\s/.test(clean)) {
      const level = Math.min(3, (clean.match(/^#+/) || ['#'])[0].length);
      return '<h' + level + '>' + escapeHtml_(clean.replace(/^#{1,3}\s*/, '')) + '</h' + level + '>';
    }
    if (/^[-•]\s+/.test(clean)) return '<li>' + escapeHtml_(clean.replace(/^[-•]\s+/, '')) + '</li>';
    return '<p>' + escapeHtml_(clean) + '</p>';
  }).join('\n');

  const html = '<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">' +
    '<title>' + escapeHtml_(title) + '</title><style>' +
    'body{margin:0;background:#05070b;color:#f4f1e8;font:17px/1.8 system-ui,sans-serif}.wrap{max-width:820px;margin:auto;padding:70px 24px}a{color:#55e6ff}h1{font-size:clamp(42px,8vw,86px);line-height:.95;letter-spacing:-.05em}h2{font-size:36px;margin-top:2em}h3{font-size:25px;margin-top:1.6em}p{color:#b0bac6}li{color:#b0bac6;margin:.5em 0}.meta{font:12px monospace;color:#55e6ff;letter-spacing:.12em;text-transform:uppercase;border-bottom:1px solid #24303e;padding-bottom:18px}</style></head>' +
    '<body><main class="wrap"><div class="meta">Guru Charan / Live learning journal</div><h1>' + escapeHtml_(title) + '</h1>' + content + '</main></body></html>';

  return HtmlService.createHtmlOutput(html)
    .setTitle(title)
    .addMetaTag('viewport', 'width=device-width, initial-scale=1');
}

function diagnostics_() {
  const properties = PropertiesService.getScriptProperties();
  return {
    ok: true,
    rootFolderConfigured: Boolean(properties.getProperty('GC_ROOT_FOLDER_ID')),
    blogsFolderConfigured: Boolean(properties.getProperty('GC_BLOGS_FOLDER_ID')),
    triggerCount: ScriptApp.getProjectTriggers().filter(function(trigger) {
      return trigger.getHandlerFunction() === 'syncFutureBlogs';
    }).length,
    contactTo: GC.CONTACT_TO,
    webAppUrl: ScriptApp.getService().getUrl(),
  };
}

function getBlogsFolder_() {
  const id = PropertiesService.getScriptProperties().getProperty('GC_BLOGS_FOLDER_ID');
  if (!id) throw new Error('Run setupPortfolioSystem() first.');
  return DriveApp.getFolderById(id);
}

function getOrCreateFolder_(parent, name) {
  const folders = parent.getFoldersByName(name);
  return folders.hasNext() ? folders.next() : parent.createFolder(name);
}

function findPrimaryDoc_(folder) {
  const files = folder.getFilesByType(MimeType.GOOGLE_DOCS);
  let selected = null;
  while (files.hasNext()) {
    const file = files.next();
    if (/^(readme|template)/i.test(file.getName())) continue;
    if (!selected || file.getLastUpdated().getTime() > selected.getLastUpdated().getTime()) selected = file;
  }
  return selected;
}

function findFile_(folder, name) {
  const files = folder.getFilesByName(name);
  return files.hasNext() ? files.next() : null;
}

function createCmsReadme_(root) {
  if (root.getFilesByName('README - Portfolio CMS.txt').hasNext()) return;
  root.createFile('README - Portfolio CMS.txt', [
    'GURU CHARAN PORTFOLIO CMS',
    '',
    'To publish a blog:',
    '1. Create a numbered folder inside Blogs, e.g. 11_New_Blog.',
    '2. Add one native Google Doc.',
    '3. Add optional metadata lines at the top:',
    'Portfolio Title: ...',
    'Portfolio Description: ...',
    'Portfolio Domain: AI & Cybersecurity',
    'Portfolio Tags: Python, SOC, Retrieval',
    'Portfolio Status: In progress',
    'Portfolio Featured: false',
    '',
    'The hourly trigger creates portfolio.meta.json automatically.',
  ].join('\n'), MimeType.PLAIN_TEXT);
}

function createBlogTemplate_(blogs) {
  const folders = blogs.getFoldersByName('00_Blog_Template');
  const folder = folders.hasNext() ? folders.next() : blogs.createFolder('00_Blog_Template');
  if (folder.getFilesByType(MimeType.GOOGLE_DOCS).hasNext()) return;

  const doc = DocumentApp.create('Template - Portfolio Blog');
  doc.getBody().setText([
    'Portfolio Title: Your public blog title',
    'Portfolio Description: A concise description for the portfolio card.',
    'Portfolio Domain: AI & Cybersecurity',
    'Portfolio Tags: Python, SOC, Retrieval',
    'Portfolio Status: In progress',
    'Portfolio Featured: false',
    '',
    '# Introduction',
    'Write the article here.',
    '',
    '# What I built',
    '',
    '# Mistakes and learning',
    '',
    '# What comes next',
  ].join('\n'));
  doc.saveAndClose();
  DriveApp.getFileById(doc.getId()).moveTo(folder);
}

function field_(lines, labels) {
  for (var i = 0; i < lines.length; i++) {
    for (var j = 0; j < labels.length; j++) {
      var match = lines[i].match(new RegExp('^' + labels[j].replace(/[.*+?^${}()|[\]\\]/g, '\\$&') + '\\s*[:–—-]\\s*(.+)$', 'i'));
      if (match) return match[1].trim();
    }
  }
  return '';
}

function descriptionFromText_(text) {
  const clean = String(text || '').replace(/\s+/g, ' ').trim();
  return clean.length > 280 ? clean.substring(0, 277).replace(/\s+\S*$/, '') + '…' : clean;
}

function inferDomain_(text) {
  const value = String(text || '').toLowerCase();
  if (/cybergpt|ra-xsoc|embedding|faiss|artificial intelligence/.test(value)) return 'AI & Cybersecurity';
  if (/soc|splunk|sysmon|kali|incident response|security/.test(value)) return 'Cybersecurity';
  if (/solar|mppt|matlab|simulink|partial shading/.test(value)) return 'Engineering Research';
  if (/sahaaya|saas|automation|apps script/.test(value)) return 'Product & Automation';
  if (/portfolio|html|css|javascript|react|web development/.test(value)) return 'Web Development';
  if (/teaching|school|student|education/.test(value)) return 'Education Technology';
  return 'Technical Learning';
}

function inferTags_(text) {
  const value = String(text || '').toLowerCase();
  const mapping = [
    ['Python', /python/], ['SOC', /\bsoc\b|security operations/], ['Cybersecurity', /cybersecurity|security/],
    ['Artificial Intelligence', /artificial intelligence|\bai\b/], ['FAISS', /faiss/],
    ['MITRE ATT&CK', /mitre/], ['Splunk', /splunk/], ['Kali Linux', /kali/],
    ['MATLAB', /matlab/], ['Simulink', /simulink/], ['Automation', /automation|apps script/],
    ['Web Development', /web development|html|css|react/],
  ];
  return mapping.filter(function(item) { return item[1].test(value); }).map(function(item) { return item[0]; }).slice(0, 9);
}

function inferStatus_(text) {
  const value = String(text || '').toLowerCase();
  if (/completed|complete/.test(value)) return 'Completed';
  if (/functional prototype|prototype/.test(value)) return 'Functional prototype';
  if (/implemented/.test(value)) return 'Implemented';
  if (/in progress|ongoing|expanding/.test(value)) return 'In progress';
  if (/research/.test(value)) return 'Research project';
  return 'Learning note';
}

function enforceContactCooldown_(email) {
  const cache = CacheService.getScriptCache();
  const key = 'contact-' + Utilities.base64EncodeWebSafe(email.toLowerCase()).substring(0, 40);
  if (cache.get(key)) throw new Error('Please wait before sending another message.');
  cache.put(key, '1', GC.CONTACT_COOLDOWN_SECONDS);
}

function clean_(value, limit) {
  return String(value || '').replace(/[\u0000-\u001F]/g, ' ').replace(/\s+/g, ' ').trim().substring(0, limit);
}

function isEmail_(value) {
  return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value);
}

function slugify_(value) {
  return String(value || '').toLowerCase().normalize('NFKD').replace(/[\u0300-\u036f]/g, '').replace(/&/g, ' and ').replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '').substring(0, 90);
}

function json_(payload) {
  return ContentService.createTextOutput(JSON.stringify(payload)).setMimeType(ContentService.MimeType.JSON);
}

function jsonOrJsonp_(payload, e) {
  const callback = String((e && e.parameter && e.parameter.callback) || '');
  if (callback && /^[a-zA-Z_$][0-9a-zA-Z_$]*$/.test(callback)) {
    return ContentService.createTextOutput(callback + '(' + JSON.stringify(payload) + ');')
      .setMimeType(ContentService.MimeType.JAVASCRIPT);
  }
  return json_(payload);
}

function escapeHtml_(value) {
  return String(value || '').replace(/[&<>"']/g, function(character) {
    return ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#039;' })[character];
  });
}
